name: CI tests

jobs:
  build:
    runs-on:  ubuntu-latest
    
    steps:
    - uses: action/checkout@v2
    - uses: action/setup-node@v1
      with:
        node-version: '14'
    - run:  npm install
    - run:  npm run test-unit
    - run:  npm run test-integration
